### ISSUE TITLE
doubt regarding on ur implementation

### ISSUE THREAD

**Issue by sai2619** [Miosp/ComfyUI-FBCNN#4]
did u run the previous paper of Towards Flexible Blind JPEG Artifacts Removal by [Jiaxi Jiang](https://paperswithcode.com/author/jiaxi-jiang),

**Comment by Miosp** [comment]
This implementation is not a rewrite, but a slight adaptation of the code in authors' [repository](https://github.com/jiaxi-jiang/FBCNN). I meant this only to be a time-saver and a convenience tool.
